schema = 3

[mod]
  [mod."ariga.io/atlas"]
    version = "v0.19.1-0.20240203083654-5948b60a8e43"
    hash = "sha256-wyuU3hcy3FbPa7iXCTGTKJ5oZH0D2SjzUZiHDGfcE+Q="
  [mod."entgo.io/ent"]
    version = "v0.14.1"
    hash = "sha256-7fZzIVIlXgxA76JgUdcD7GQQYA1hXoGg9MUYDEbAZcA="
  [mod."github.com/a-h/templ"]
    version = "v0.2.778"
    hash = "sha256-54iSeNJU4dMMkxHEh0KyRu//vADMnt93fjmXzqc2xPE="
  [mod."github.com/agext/levenshtein"]
    version = "v1.2.1"
    hash = "sha256-SuFgpvp7KGO4f2t0KnkhSUv7iRI7oGq40CjRc1tLNr4="
  [mod."github.com/apparentlymart/go-textseg/v13"]
    version = "v13.0.0"
    hash = "sha256-Hn+zO0J/vnG5U6JvZfRyWm8vsqYdjh4RAreWnZLCQKQ="
  [mod."github.com/go-openapi/inflect"]
    version = "v0.19.0"
    hash = "sha256-jS969dMoR2zLfVfsIQoQIbATyE5p2mIZfW9SnxY7W68="
  [mod."github.com/golang-jwt/jwt"]
    version = "v3.2.2+incompatible"
    hash = "sha256-LOkpuXhWrFayvVf1GOaOmZI5YKEsgqVSb22aF8LnCEM="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/hashicorp/hcl/v2"]
    version = "v2.13.0"
    hash = "sha256-Y67be1wd7PI7Rmc4tX3klCE7fCokhZuvbXFmbfD1Htc="
  [mod."github.com/joho/godotenv"]
    version = "v1.5.1"
    hash = "sha256-kA0osKfsc6Kp+nuGTRJyXZZlJt1D/kuEazKMWYCWcQ8="
  [mod."github.com/labstack/echo/v4"]
    version = "v4.12.0"
    hash = "sha256-TPXJv/6C53bnmcEYxa9g5Mft8u/rLT96q64tQ9+RtKU="
  [mod."github.com/labstack/gommon"]
    version = "v0.4.2"
    hash = "sha256-395+BETDpv15L2lsCiEccwakXgEQxKHlYBAU0Ot3qhY="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.16"
    hash = "sha256-Ky0kas72AY0lpuRiC/fQk9rw9aJ6dvL9y1Ikw5PFzlA="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v0.0.0-20150314170334-ad45545899c7"
    hash = "sha256-aR+xW4TnVo96Cbw168fhdIBEh7O43mOlHdLx/WxrwVs="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasttemplate"]
    version = "v1.2.2"
    hash = "sha256-gp+lNXE8zjO+qJDM/YbS6V43HFsYP6PKn4ux1qa5lZ0="
  [mod."github.com/zclconf/go-cty"]
    version = "v1.8.0"
    hash = "sha256-Sf4mCSBV8e53x8nI0YPgZHivNWmUseWc26AtTdcUv4c="
  [mod."golang.org/x/crypto"]
    version = "v0.26.0"
    hash = "sha256-Iicrsb65fCmjfPILKoSLyBZMwe2VUcoTF5SpYTCQEuk="
  [mod."golang.org/x/mod"]
    version = "v0.20.0"
    hash = "sha256-nXYnY2kpbVkaZ/7Mf7FmxwGDX7N4cID3gKjGghmVRp4="
  [mod."golang.org/x/net"]
    version = "v0.28.0"
    hash = "sha256-WdH/mgsX/CB+CiYtXEwJAXHN8FgtW2YhFcWwrrHNBLo="
  [mod."golang.org/x/sys"]
    version = "v0.24.0"
    hash = "sha256-P0fsA+qy9taYHWPTtCs5XmrJ1i8tWfvkno+PNuc2elw="
  [mod."golang.org/x/text"]
    version = "v0.17.0"
    hash = "sha256-R8JbsP7KX+KFTHH7SjRnUGCdvtagylVOfngWEnVSqBc="
  [mod."golang.org/x/time"]
    version = "v0.6.0"
    hash = "sha256-gW9TVK9HjLk52lzfo5rBzSunc01gS0+SG2nk0X1w55M="
