schema = 3

[mod]
  [mod."github.com/AlecAivazis/survey/v2"]
    version = "v2.3.7"
    hash = "sha256-JY3+GFN+m/sew7jq9pfuV4aWFmrGxMLN6kkBrVXDoMs="
  [mod."github.com/a-h/templ"]
    version = "v0.2.778"
    hash = "sha256-54iSeNJU4dMMkxHEh0KyRu//vADMnt93fjmXzqc2xPE="
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20230301143203-a9d515a09cc2"
    hash = "sha256-UCENzt1c1tFgsAzK2TNq5s2g0tQMQ5PxFaQKe8hTL/A="
  [mod."github.com/aws/aws-sdk-go-v2"]
    version = "v1.30.4"
    hash = "sha256-PdGytPmOIOg1u8My/E6nDFKqEW4s9/YNcVqUAoNTMG4="
  [mod."github.com/aws/aws-sdk-go-v2/aws/protocol/eventstream"]
    version = "v1.6.4"
    hash = "sha256-tDMhNhNZ1bjkN+0EBXeGHgEVpx602+5LM18B42m9K6c="
  [mod."github.com/aws/aws-sdk-go-v2/config"]
    version = "v1.27.31"
    hash = "sha256-DrzFkXbOEIyjjxU5pu6KpYk8BINWywaoPclwmRNFMc8="
  [mod."github.com/aws/aws-sdk-go-v2/credentials"]
    version = "v1.17.30"
    hash = "sha256-yhfJa2vzmy4itz9wqiMntmM9+ur6tTohrqL0OCd5FiI="
  [mod."github.com/aws/aws-sdk-go-v2/feature/ec2/imds"]
    version = "v1.16.12"
    hash = "sha256-on45jRfZK3MwCVno5TdiaykjRWkd66PC7mRH54QXKt0="
  [mod."github.com/aws/aws-sdk-go-v2/feature/s3/manager"]
    version = "v1.17.15"
    hash = "sha256-X3b9I3Ri5QrR9t/s03elY89CPMCvbeYDm0/aZP4C2bI="
  [mod."github.com/aws/aws-sdk-go-v2/internal/configsources"]
    version = "v1.3.16"
    hash = "sha256-re3b54TTYwrhXKS58eooKzAi7YLx5HMhBDYePMPJQ2Y="
  [mod."github.com/aws/aws-sdk-go-v2/internal/endpoints/v2"]
    version = "v2.6.16"
    hash = "sha256-rzxM1yqbFtJYM93aPmHbn+XeIOxSDBzSkKTgBMJchVc="
  [mod."github.com/aws/aws-sdk-go-v2/internal/ini"]
    version = "v1.8.1"
    hash = "sha256-xinXoaSTaE4p/Li9h3nE8t7Y0uM6OFX/qkS+sCHQtp4="
  [mod."github.com/aws/aws-sdk-go-v2/internal/v4a"]
    version = "v1.3.16"
    hash = "sha256-LmAkGnno26os5UkowzJQxxG9iCN5iG9j9qTs6keY78o="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/accept-encoding"]
    version = "v1.11.4"
    hash = "sha256-wtbi90iuux1ISaadbK7h4QkOuWb0Naxzis2VoNF1V0E="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/checksum"]
    version = "v1.3.18"
    hash = "sha256-Kn0mtlAqZe/dhGbDbszUYWy55hJis4UISfGdbK/61Bw="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/presigned-url"]
    version = "v1.11.18"
    hash = "sha256-t8X9ZtA8gL5KYgIjZZ2HsG3V7siM+MKenAKBXwgoWa8="
  [mod."github.com/aws/aws-sdk-go-v2/service/internal/s3shared"]
    version = "v1.17.16"
    hash = "sha256-rLXwyqUl7Nd+sSMMVaXTvIxZUGnkOeGZ5jUR19hLTYM="
  [mod."github.com/aws/aws-sdk-go-v2/service/s3"]
    version = "v1.60.1"
    hash = "sha256-cXvR7dJWNq5ris16RG9BSpl1ljhY5GRp8ioZgRYIL54="
  [mod."github.com/aws/aws-sdk-go-v2/service/sso"]
    version = "v1.22.5"
    hash = "sha256-5nmEul6XyiqMFQu2ydilRk4lko+645PaPVFeke7zoAM="
  [mod."github.com/aws/aws-sdk-go-v2/service/ssooidc"]
    version = "v1.26.5"
    hash = "sha256-bE6wPVWioEI+tt2JaMJGKzVcjioIV/MXseHkuGqB7Mk="
  [mod."github.com/aws/aws-sdk-go-v2/service/sts"]
    version = "v1.30.5"
    hash = "sha256-Z8OY5gliwSnEzet0K3NKlDFmXboYdT9lObEEslt2mRY="
  [mod."github.com/aws/smithy-go"]
    version = "v1.20.4"
    hash = "sha256-lli4lJ5s3i3T97SLFjlUDDR0SDOYTRbvOq3nHKPQk7U="
  [mod."github.com/disintegration/imaging"]
    version = "v1.6.2"
    hash = "sha256-pSeMTPvSkxlthh65LjNYYhPLvCZDkBgVgAGYWW0Aguo="
  [mod."github.com/domodwyer/mailyak/v3"]
    version = "v3.6.2"
    hash = "sha256-V4zP5GBwiUq5gScNO/XN/dbwJRBawwnUYw+WfUPbsbQ="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/fatih/color"]
    version = "v1.17.0"
    hash = "sha256-QsKMy3MsvjbYNcA9jP8w6c3wpmWDZ0079bybAEzmXR0="
  [mod."github.com/gabriel-vasile/mimetype"]
    version = "v1.4.5"
    hash = "sha256-Vv/+Et/6G+eFKehBx1dhqommo/bs7qXrgDzzu18G4FM="
  [mod."github.com/ganigeorgiev/fexpr"]
    version = "v0.4.1"
    hash = "sha256-TEOOTjJ3fQyiRMPB0UJLIO/VSaBAyYjfIqdzdzCqFJg="
  [mod."github.com/go-ozzo/ozzo-validation/v4"]
    version = "v4.3.0"
    hash = "sha256-iCpu3UZK24NiJ7FThrGbC5/683JKypeLeHC6L2dvVIg="
  [mod."github.com/goccy/go-json"]
    version = "v0.10.3"
    hash = "sha256-ZOzfwCXh+qp+hp+UnC0t422hUV0Cq5KANXkx8hcLp7s="
  [mod."github.com/golang-jwt/jwt/v4"]
    version = "v4.5.0"
    hash = "sha256-dyKL8wQRApkdCkKxJ1knllvixsrBLw+BtRS0SjlN7NQ="
  [mod."github.com/golang/groupcache"]
    version = "v0.0.0-20210331224755-41bb18bfe9da"
    hash = "sha256-7Gs7CS9gEYZkbu5P4hqPGBpeGZWC64VDwraSKFF+VR0="
  [mod."github.com/google/uuid"]
    version = "v1.6.0"
    hash = "sha256-VWl9sqUzdOuhW0KzQlv0gwwUQClYkmZwSydHG2sALYw="
  [mod."github.com/googleapis/gax-go/v2"]
    version = "v2.13.0"
    hash = "sha256-p1SEjRjI/SkWSBWjeptQ5M/Tgrcj8IiH/beXBYqRVko="
  [mod."github.com/hashicorp/golang-lru/v2"]
    version = "v2.0.7"
    hash = "sha256-t1bcXLgrQNOYUVyYEZ0knxcXpsTk4IuJZDjKvyJX75g="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/kballard/go-shellquote"]
    version = "v0.0.0-20180428030007-95032a82bc51"
    hash = "sha256-AOEdKETBMUC39ln6jBJ9NYdJWp++jV5lSbjNqG3dV+c="
  [mod."github.com/labstack/echo/v5"]
    version = "v5.0.0-20230722203903-ec5b858dab61"
    hash = "sha256-OlRbw7jfFjtfklmbGHcx8QSF4WHfbKILUq1RzDcWT1w="
  [mod."github.com/mattn/go-colorable"]
    version = "v0.1.13"
    hash = "sha256-qb3Qbo0CELGRIzvw7NVM1g/aayaz4Tguppk9MD2/OI8="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mattn/go-sqlite3"]
    version = "v1.14.22"
    hash = "sha256-CWF2Hjg43658NhaePWbGzS19gHJXjuTroG5c0W3hgYQ="
  [mod."github.com/mgutz/ansi"]
    version = "v0.0.0-20200706080929-d51e80ef957d"
    hash = "sha256-RY6deYqJKpTTttr5tH2VW+PtuUIcieEq3Y6fGqRL0vk="
  [mod."github.com/ncruces/go-strftime"]
    version = "v0.1.9"
    hash = "sha256-T0iw+UEckzueWHT88PkTnZZixyKCEa+DTLzIiiohuWY="
  [mod."github.com/pocketbase/dbx"]
    version = "v1.10.1"
    hash = "sha256-EyXR9hLZYmz57wPHtFign6yOE5GT3kNrX21j4r03qQw="
  [mod."github.com/pocketbase/pocketbase"]
    version = "v0.22.21"
    hash = "sha256-xEU1W9n61sKG4723i9o0CdqOxIHfbTlfG4LPL8XAOEg="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/spf13/cast"]
    version = "v1.7.0"
    hash = "sha256-xO2kSmNmMHaJ1i3T0ou0pcaBCusuO6Ep3xtF1P7ZadA="
  [mod."github.com/spf13/cobra"]
    version = "v1.8.1"
    hash = "sha256-yDF6yAHycV1IZOrt3/hofR+QINe+B2yqkcIaVov3Ky8="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/valyala/bytebufferpool"]
    version = "v1.0.0"
    hash = "sha256-I9FPZ3kCNRB+o0dpMwBnwZ35Fj9+ThvITn8a3Jr8mAY="
  [mod."github.com/valyala/fasttemplate"]
    version = "v1.2.2"
    hash = "sha256-gp+lNXE8zjO+qJDM/YbS6V43HFsYP6PKn4ux1qa5lZ0="
  [mod."go.opencensus.io"]
    version = "v0.24.0"
    hash = "sha256-4H+mGZgG2c9I1y0m8avF4qmt8LUKxxVsTqR8mKgP4yo="
  [mod."gocloud.dev"]
    version = "v0.39.0"
    hash = "sha256-EepaYJ8w6Wl8fYfiXc7I3cpa6D4qJEUxTK9F1S3Ayjo="
  [mod."golang.org/x/crypto"]
    version = "v0.26.0"
    hash = "sha256-Iicrsb65fCmjfPILKoSLyBZMwe2VUcoTF5SpYTCQEuk="
  [mod."golang.org/x/image"]
    version = "v0.19.0"
    hash = "sha256-IPl8LVdhq8YNxFBgnVa5k64J3zZjuE99TxrkDvzmYVk="
  [mod."golang.org/x/net"]
    version = "v0.28.0"
    hash = "sha256-WdH/mgsX/CB+CiYtXEwJAXHN8FgtW2YhFcWwrrHNBLo="
  [mod."golang.org/x/oauth2"]
    version = "v0.22.0"
    hash = "sha256-3gmmXfCcxYBMaXmKRzGBpX01h4lMenFPkqWT9TwqIBE="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.24.0"
    hash = "sha256-P0fsA+qy9taYHWPTtCs5XmrJ1i8tWfvkno+PNuc2elw="
  [mod."golang.org/x/term"]
    version = "v0.23.0"
    hash = "sha256-ECmmK3Wc0g/zUy5wAokj7ItRsUi6eoqSe9s9Uhcwu90="
  [mod."golang.org/x/text"]
    version = "v0.17.0"
    hash = "sha256-R8JbsP7KX+KFTHH7SjRnUGCdvtagylVOfngWEnVSqBc="
  [mod."golang.org/x/time"]
    version = "v0.6.0"
    hash = "sha256-gW9TVK9HjLk52lzfo5rBzSunc01gS0+SG2nk0X1w55M="
  [mod."golang.org/x/xerrors"]
    version = "v0.0.0-20240716161551-93cc26a95ae9"
    hash = "sha256-HGy/sKQFxPosN1FRtLcBYvyTfk6tlk2lnz2AKD7HiHM="
  [mod."google.golang.org/api"]
    version = "v0.194.0"
    hash = "sha256-WJZ6BT3v+fFRij1Ke5PRhP0R2C7hy6IoxGXL+Gjg+oY="
  [mod."google.golang.org/genproto/googleapis/rpc"]
    version = "v0.0.0-20240827150818-7e3bb234dfed"
    hash = "sha256-4T4DTrmFbqT4tD7PSL7Ie7u8ZN2iwGkhK02nWugssxk="
  [mod."google.golang.org/grpc"]
    version = "v1.65.0"
    hash = "sha256-YP4dewjs+YuTH7rD1p/AFNoKHlk037wbVvSLVAtewIA="
  [mod."google.golang.org/protobuf"]
    version = "v1.34.2"
    hash = "sha256-nMTlrDEE2dbpWz50eQMPBQXCyQh4IdjrTIccaU0F3m0="
  [mod."modernc.org/gc/v3"]
    version = "v3.0.0-20240801135723-a856999a2e4a"
    hash = "sha256-mNcc0Tw2uVVb9YzBUhZ5POHxBiUnCckQywHm/p9NI9s="
  [mod."modernc.org/libc"]
    version = "v1.55.3"
    hash = "sha256-MGEOCkVDhjZW0t68m5p45UjikILl59KoL/3wx65O1zs="
  [mod."modernc.org/mathutil"]
    version = "v1.6.0"
    hash = "sha256-lfuEiS1odd2TWrTylnaGihSJ9myqKs3FLdpvd7PqTnE="
  [mod."modernc.org/memory"]
    version = "v1.8.0"
    hash = "sha256-ucvPr73zg8LjvU+bcoIPKTgwgcon3U9VhKrLEMH81xg="
  [mod."modernc.org/sqlite"]
    version = "v1.32.0"
    hash = "sha256-RHIhxRmovkIngrjC+DqOydhTSd3TwtYARuZKWInZdks="
  [mod."modernc.org/strutil"]
    version = "v1.2.0"
    hash = "sha256-NTYIWMRZjHmR77LMvsFOMCitt7toKTfH+zChYAMzZ2Y="
  [mod."modernc.org/token"]
    version = "v1.1.0"
    hash = "sha256-m8WyXJ9Mdw6B43wmy2+3HE7zHEi9ocBrhwe/eq+zdu8="
