//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Externalauths struct {
	ID           string `sql:"primary_key"`
	CollectionId string
	RecordId     string
	Provider     string
	ProviderId   string
	Created      string
	Updated      string
}
