//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Guesses struct {
	Created     string
	GuessedTime string
	ID          string `sql:"primary_key"`
	Message     string
	StartTime   string
	Updated     string
	Winner      string
}
