//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Users struct {
	Avatar                 string
	Created                string
	Email                  string
	EmailVisibility        bool
	ID                     string `sql:"primary_key"`
	LastLoginAlertSentAt   string
	LastResetSentAt        string
	LastVerificationSentAt string
	Name                   string
	PasswordHash           string
	TokenKey               string
	Updated                string
	Username               string
	Verified               bool
}
