// Code generated by ent, DO NOT EDIT.

package messagescore

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lukepeltier/discordle/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldLTE(FieldID, id))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldEQ(FieldScore, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v uint16) predicate.MessageScore {
	return predicate.MessageScore(sql.FieldLTE(FieldScore, v))
}

// HasMessage applies the HasEdge predicate on the "message" edge.
func HasMessage() predicate.MessageScore {
	return predicate.MessageScore(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MessageTable, MessageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessageWith applies the HasEdge predicate on the "message" edge with a given conditions (other predicates).
func HasMessageWith(preds ...predicate.Message) predicate.MessageScore {
	return predicate.MessageScore(func(s *sql.Selector) {
		step := newMessageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MessageScore) predicate.MessageScore {
	return predicate.MessageScore(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MessageScore) predicate.MessageScore {
	return predicate.MessageScore(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MessageScore) predicate.MessageScore {
	return predicate.MessageScore(sql.NotPredicates(p))
}
