// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lukepeltier/discordle/ent/discordmember"
	"github.com/lukepeltier/discordle/ent/message"
	"github.com/lukepeltier/discordle/ent/predicate"
)

// DiscordMemberQuery is the builder for querying DiscordMember entities.
type DiscordMemberQuery struct {
	config
	ctx          *QueryContext
	order        []discordmember.OrderOption
	inters       []Interceptor
	predicates   []predicate.DiscordMember
	withMessages *MessageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DiscordMemberQuery builder.
func (dmq *DiscordMemberQuery) Where(ps ...predicate.DiscordMember) *DiscordMemberQuery {
	dmq.predicates = append(dmq.predicates, ps...)
	return dmq
}

// Limit the number of records to be returned by this query.
func (dmq *DiscordMemberQuery) Limit(limit int) *DiscordMemberQuery {
	dmq.ctx.Limit = &limit
	return dmq
}

// Offset to start from.
func (dmq *DiscordMemberQuery) Offset(offset int) *DiscordMemberQuery {
	dmq.ctx.Offset = &offset
	return dmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dmq *DiscordMemberQuery) Unique(unique bool) *DiscordMemberQuery {
	dmq.ctx.Unique = &unique
	return dmq
}

// Order specifies how the records should be ordered.
func (dmq *DiscordMemberQuery) Order(o ...discordmember.OrderOption) *DiscordMemberQuery {
	dmq.order = append(dmq.order, o...)
	return dmq
}

// QueryMessages chains the current query on the "messages" edge.
func (dmq *DiscordMemberQuery) QueryMessages() *MessageQuery {
	query := (&MessageClient{config: dmq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(discordmember.Table, discordmember.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, discordmember.MessagesTable, discordmember.MessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(dmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DiscordMember entity from the query.
// Returns a *NotFoundError when no DiscordMember was found.
func (dmq *DiscordMemberQuery) First(ctx context.Context) (*DiscordMember, error) {
	nodes, err := dmq.Limit(1).All(setContextOp(ctx, dmq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{discordmember.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dmq *DiscordMemberQuery) FirstX(ctx context.Context) *DiscordMember {
	node, err := dmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DiscordMember ID from the query.
// Returns a *NotFoundError when no DiscordMember ID was found.
func (dmq *DiscordMemberQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dmq.Limit(1).IDs(setContextOp(ctx, dmq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{discordmember.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dmq *DiscordMemberQuery) FirstIDX(ctx context.Context) int {
	id, err := dmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DiscordMember entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DiscordMember entity is found.
// Returns a *NotFoundError when no DiscordMember entities are found.
func (dmq *DiscordMemberQuery) Only(ctx context.Context) (*DiscordMember, error) {
	nodes, err := dmq.Limit(2).All(setContextOp(ctx, dmq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{discordmember.Label}
	default:
		return nil, &NotSingularError{discordmember.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dmq *DiscordMemberQuery) OnlyX(ctx context.Context) *DiscordMember {
	node, err := dmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DiscordMember ID in the query.
// Returns a *NotSingularError when more than one DiscordMember ID is found.
// Returns a *NotFoundError when no entities are found.
func (dmq *DiscordMemberQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = dmq.Limit(2).IDs(setContextOp(ctx, dmq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{discordmember.Label}
	default:
		err = &NotSingularError{discordmember.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dmq *DiscordMemberQuery) OnlyIDX(ctx context.Context) int {
	id, err := dmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DiscordMembers.
func (dmq *DiscordMemberQuery) All(ctx context.Context) ([]*DiscordMember, error) {
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryAll)
	if err := dmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DiscordMember, *DiscordMemberQuery]()
	return withInterceptors[[]*DiscordMember](ctx, dmq, qr, dmq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dmq *DiscordMemberQuery) AllX(ctx context.Context) []*DiscordMember {
	nodes, err := dmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DiscordMember IDs.
func (dmq *DiscordMemberQuery) IDs(ctx context.Context) (ids []int, err error) {
	if dmq.ctx.Unique == nil && dmq.path != nil {
		dmq.Unique(true)
	}
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryIDs)
	if err = dmq.Select(discordmember.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dmq *DiscordMemberQuery) IDsX(ctx context.Context) []int {
	ids, err := dmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dmq *DiscordMemberQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryCount)
	if err := dmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dmq, querierCount[*DiscordMemberQuery](), dmq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dmq *DiscordMemberQuery) CountX(ctx context.Context) int {
	count, err := dmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dmq *DiscordMemberQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dmq.ctx, ent.OpQueryExist)
	switch _, err := dmq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dmq *DiscordMemberQuery) ExistX(ctx context.Context) bool {
	exist, err := dmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DiscordMemberQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dmq *DiscordMemberQuery) Clone() *DiscordMemberQuery {
	if dmq == nil {
		return nil
	}
	return &DiscordMemberQuery{
		config:       dmq.config,
		ctx:          dmq.ctx.Clone(),
		order:        append([]discordmember.OrderOption{}, dmq.order...),
		inters:       append([]Interceptor{}, dmq.inters...),
		predicates:   append([]predicate.DiscordMember{}, dmq.predicates...),
		withMessages: dmq.withMessages.Clone(),
		// clone intermediate query.
		sql:  dmq.sql.Clone(),
		path: dmq.path,
	}
}

// WithMessages tells the query-builder to eager-load the nodes that are connected to
// the "messages" edge. The optional arguments are used to configure the query builder of the edge.
func (dmq *DiscordMemberQuery) WithMessages(opts ...func(*MessageQuery)) *DiscordMemberQuery {
	query := (&MessageClient{config: dmq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dmq.withMessages = query
	return dmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DiscordMember.Query().
//		GroupBy(discordmember.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dmq *DiscordMemberQuery) GroupBy(field string, fields ...string) *DiscordMemberGroupBy {
	dmq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DiscordMemberGroupBy{build: dmq}
	grbuild.flds = &dmq.ctx.Fields
	grbuild.label = discordmember.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.DiscordMember.Query().
//		Select(discordmember.FieldUsername).
//		Scan(ctx, &v)
func (dmq *DiscordMemberQuery) Select(fields ...string) *DiscordMemberSelect {
	dmq.ctx.Fields = append(dmq.ctx.Fields, fields...)
	sbuild := &DiscordMemberSelect{DiscordMemberQuery: dmq}
	sbuild.label = discordmember.Label
	sbuild.flds, sbuild.scan = &dmq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DiscordMemberSelect configured with the given aggregations.
func (dmq *DiscordMemberQuery) Aggregate(fns ...AggregateFunc) *DiscordMemberSelect {
	return dmq.Select().Aggregate(fns...)
}

func (dmq *DiscordMemberQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dmq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dmq); err != nil {
				return err
			}
		}
	}
	for _, f := range dmq.ctx.Fields {
		if !discordmember.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dmq.path != nil {
		prev, err := dmq.path(ctx)
		if err != nil {
			return err
		}
		dmq.sql = prev
	}
	return nil
}

func (dmq *DiscordMemberQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DiscordMember, error) {
	var (
		nodes       = []*DiscordMember{}
		_spec       = dmq.querySpec()
		loadedTypes = [1]bool{
			dmq.withMessages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DiscordMember).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DiscordMember{config: dmq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dmq.withMessages; query != nil {
		if err := dmq.loadMessages(ctx, query, nodes,
			func(n *DiscordMember) { n.Edges.Messages = []*Message{} },
			func(n *DiscordMember, e *Message) { n.Edges.Messages = append(n.Edges.Messages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dmq *DiscordMemberQuery) loadMessages(ctx context.Context, query *MessageQuery, nodes []*DiscordMember, init func(*DiscordMember), assign func(*DiscordMember, *Message)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*DiscordMember)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Message(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(discordmember.MessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.discord_member_messages
		if fk == nil {
			return fmt.Errorf(`foreign-key "discord_member_messages" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "discord_member_messages" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (dmq *DiscordMemberQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dmq.querySpec()
	_spec.Node.Columns = dmq.ctx.Fields
	if len(dmq.ctx.Fields) > 0 {
		_spec.Unique = dmq.ctx.Unique != nil && *dmq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dmq.driver, _spec)
}

func (dmq *DiscordMemberQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(discordmember.Table, discordmember.Columns, sqlgraph.NewFieldSpec(discordmember.FieldID, field.TypeInt))
	_spec.From = dmq.sql
	if unique := dmq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dmq.path != nil {
		_spec.Unique = true
	}
	if fields := dmq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, discordmember.FieldID)
		for i := range fields {
			if fields[i] != discordmember.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := dmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dmq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dmq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dmq *DiscordMemberQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dmq.driver.Dialect())
	t1 := builder.Table(discordmember.Table)
	columns := dmq.ctx.Fields
	if len(columns) == 0 {
		columns = discordmember.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dmq.sql != nil {
		selector = dmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dmq.ctx.Unique != nil && *dmq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dmq.predicates {
		p(selector)
	}
	for _, p := range dmq.order {
		p(selector)
	}
	if offset := dmq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dmq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DiscordMemberGroupBy is the group-by builder for DiscordMember entities.
type DiscordMemberGroupBy struct {
	selector
	build *DiscordMemberQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dmgb *DiscordMemberGroupBy) Aggregate(fns ...AggregateFunc) *DiscordMemberGroupBy {
	dmgb.fns = append(dmgb.fns, fns...)
	return dmgb
}

// Scan applies the selector query and scans the result into the given value.
func (dmgb *DiscordMemberGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dmgb.build.ctx, ent.OpQueryGroupBy)
	if err := dmgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiscordMemberQuery, *DiscordMemberGroupBy](ctx, dmgb.build, dmgb, dmgb.build.inters, v)
}

func (dmgb *DiscordMemberGroupBy) sqlScan(ctx context.Context, root *DiscordMemberQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dmgb.fns))
	for _, fn := range dmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dmgb.flds)+len(dmgb.fns))
		for _, f := range *dmgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dmgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dmgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DiscordMemberSelect is the builder for selecting fields of DiscordMember entities.
type DiscordMemberSelect struct {
	*DiscordMemberQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dms *DiscordMemberSelect) Aggregate(fns ...AggregateFunc) *DiscordMemberSelect {
	dms.fns = append(dms.fns, fns...)
	return dms
}

// Scan applies the selector query and scans the result into the given value.
func (dms *DiscordMemberSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dms.ctx, ent.OpQuerySelect)
	if err := dms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DiscordMemberQuery, *DiscordMemberSelect](ctx, dms.DiscordMemberQuery, dms, dms.inters, v)
}

func (dms *DiscordMemberSelect) sqlScan(ctx context.Context, root *DiscordMemberQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dms.fns))
	for _, fn := range dms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
