// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lukepeltier/discordle/ent/message"
	"github.com/lukepeltier/discordle/ent/messagescore"
	"github.com/lukepeltier/discordle/ent/predicate"
)

// MessageScoreQuery is the builder for querying MessageScore entities.
type MessageScoreQuery struct {
	config
	ctx         *QueryContext
	order       []messagescore.OrderOption
	inters      []Interceptor
	predicates  []predicate.MessageScore
	withMessage *MessageQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MessageScoreQuery builder.
func (msq *MessageScoreQuery) Where(ps ...predicate.MessageScore) *MessageScoreQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit the number of records to be returned by this query.
func (msq *MessageScoreQuery) Limit(limit int) *MessageScoreQuery {
	msq.ctx.Limit = &limit
	return msq
}

// Offset to start from.
func (msq *MessageScoreQuery) Offset(offset int) *MessageScoreQuery {
	msq.ctx.Offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MessageScoreQuery) Unique(unique bool) *MessageScoreQuery {
	msq.ctx.Unique = &unique
	return msq
}

// Order specifies how the records should be ordered.
func (msq *MessageScoreQuery) Order(o ...messagescore.OrderOption) *MessageScoreQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// QueryMessage chains the current query on the "message" edge.
func (msq *MessageScoreQuery) QueryMessage() *MessageQuery {
	query := (&MessageClient{config: msq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := msq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(messagescore.Table, messagescore.FieldID, selector),
			sqlgraph.To(message.Table, message.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, messagescore.MessageTable, messagescore.MessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(msq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MessageScore entity from the query.
// Returns a *NotFoundError when no MessageScore was found.
func (msq *MessageScoreQuery) First(ctx context.Context) (*MessageScore, error) {
	nodes, err := msq.Limit(1).All(setContextOp(ctx, msq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{messagescore.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MessageScoreQuery) FirstX(ctx context.Context) *MessageScore {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MessageScore ID from the query.
// Returns a *NotFoundError when no MessageScore ID was found.
func (msq *MessageScoreQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(1).IDs(setContextOp(ctx, msq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{messagescore.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MessageScoreQuery) FirstIDX(ctx context.Context) int {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MessageScore entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MessageScore entity is found.
// Returns a *NotFoundError when no MessageScore entities are found.
func (msq *MessageScoreQuery) Only(ctx context.Context) (*MessageScore, error) {
	nodes, err := msq.Limit(2).All(setContextOp(ctx, msq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{messagescore.Label}
	default:
		return nil, &NotSingularError{messagescore.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MessageScoreQuery) OnlyX(ctx context.Context) *MessageScore {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MessageScore ID in the query.
// Returns a *NotSingularError when more than one MessageScore ID is found.
// Returns a *NotFoundError when no entities are found.
func (msq *MessageScoreQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(2).IDs(setContextOp(ctx, msq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{messagescore.Label}
	default:
		err = &NotSingularError{messagescore.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MessageScoreQuery) OnlyIDX(ctx context.Context) int {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MessageScores.
func (msq *MessageScoreQuery) All(ctx context.Context) ([]*MessageScore, error) {
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryAll)
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MessageScore, *MessageScoreQuery]()
	return withInterceptors[[]*MessageScore](ctx, msq, qr, msq.inters)
}

// AllX is like All, but panics if an error occurs.
func (msq *MessageScoreQuery) AllX(ctx context.Context) []*MessageScore {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MessageScore IDs.
func (msq *MessageScoreQuery) IDs(ctx context.Context) (ids []int, err error) {
	if msq.ctx.Unique == nil && msq.path != nil {
		msq.Unique(true)
	}
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryIDs)
	if err = msq.Select(messagescore.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MessageScoreQuery) IDsX(ctx context.Context) []int {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MessageScoreQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryCount)
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, msq, querierCount[*MessageScoreQuery](), msq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MessageScoreQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MessageScoreQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, msq.ctx, ent.OpQueryExist)
	switch _, err := msq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MessageScoreQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MessageScoreQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MessageScoreQuery) Clone() *MessageScoreQuery {
	if msq == nil {
		return nil
	}
	return &MessageScoreQuery{
		config:      msq.config,
		ctx:         msq.ctx.Clone(),
		order:       append([]messagescore.OrderOption{}, msq.order...),
		inters:      append([]Interceptor{}, msq.inters...),
		predicates:  append([]predicate.MessageScore{}, msq.predicates...),
		withMessage: msq.withMessage.Clone(),
		// clone intermediate query.
		sql:  msq.sql.Clone(),
		path: msq.path,
	}
}

// WithMessage tells the query-builder to eager-load the nodes that are connected to
// the "message" edge. The optional arguments are used to configure the query builder of the edge.
func (msq *MessageScoreQuery) WithMessage(opts ...func(*MessageQuery)) *MessageScoreQuery {
	query := (&MessageClient{config: msq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	msq.withMessage = query
	return msq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Score uint16 `json:"score,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MessageScore.Query().
//		GroupBy(messagescore.FieldScore).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (msq *MessageScoreQuery) GroupBy(field string, fields ...string) *MessageScoreGroupBy {
	msq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MessageScoreGroupBy{build: msq}
	grbuild.flds = &msq.ctx.Fields
	grbuild.label = messagescore.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Score uint16 `json:"score,omitempty"`
//	}
//
//	client.MessageScore.Query().
//		Select(messagescore.FieldScore).
//		Scan(ctx, &v)
func (msq *MessageScoreQuery) Select(fields ...string) *MessageScoreSelect {
	msq.ctx.Fields = append(msq.ctx.Fields, fields...)
	sbuild := &MessageScoreSelect{MessageScoreQuery: msq}
	sbuild.label = messagescore.Label
	sbuild.flds, sbuild.scan = &msq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MessageScoreSelect configured with the given aggregations.
func (msq *MessageScoreQuery) Aggregate(fns ...AggregateFunc) *MessageScoreSelect {
	return msq.Select().Aggregate(fns...)
}

func (msq *MessageScoreQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range msq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, msq); err != nil {
				return err
			}
		}
	}
	for _, f := range msq.ctx.Fields {
		if !messagescore.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MessageScoreQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MessageScore, error) {
	var (
		nodes       = []*MessageScore{}
		withFKs     = msq.withFKs
		_spec       = msq.querySpec()
		loadedTypes = [1]bool{
			msq.withMessage != nil,
		}
	)
	if msq.withMessage != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, messagescore.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MessageScore).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MessageScore{config: msq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := msq.withMessage; query != nil {
		if err := msq.loadMessage(ctx, query, nodes, nil,
			func(n *MessageScore, e *Message) { n.Edges.Message = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (msq *MessageScoreQuery) loadMessage(ctx context.Context, query *MessageQuery, nodes []*MessageScore, init func(*MessageScore), assign func(*MessageScore, *Message)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*MessageScore)
	for i := range nodes {
		if nodes[i].message_score_message == nil {
			continue
		}
		fk := *nodes[i].message_score_message
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(message.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "message_score_message" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (msq *MessageScoreQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	_spec.Node.Columns = msq.ctx.Fields
	if len(msq.ctx.Fields) > 0 {
		_spec.Unique = msq.ctx.Unique != nil && *msq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MessageScoreQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(messagescore.Table, messagescore.Columns, sqlgraph.NewFieldSpec(messagescore.FieldID, field.TypeInt))
	_spec.From = msq.sql
	if unique := msq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if msq.path != nil {
		_spec.Unique = true
	}
	if fields := msq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, messagescore.FieldID)
		for i := range fields {
			if fields[i] != messagescore.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MessageScoreQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(messagescore.Table)
	columns := msq.ctx.Fields
	if len(columns) == 0 {
		columns = messagescore.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if msq.ctx.Unique != nil && *msq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MessageScoreGroupBy is the group-by builder for MessageScore entities.
type MessageScoreGroupBy struct {
	selector
	build *MessageScoreQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MessageScoreGroupBy) Aggregate(fns ...AggregateFunc) *MessageScoreGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the selector query and scans the result into the given value.
func (msgb *MessageScoreGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, msgb.build.ctx, ent.OpQueryGroupBy)
	if err := msgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageScoreQuery, *MessageScoreGroupBy](ctx, msgb.build, msgb, msgb.build.inters, v)
}

func (msgb *MessageScoreGroupBy) sqlScan(ctx context.Context, root *MessageScoreQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*msgb.flds)+len(msgb.fns))
		for _, f := range *msgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*msgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MessageScoreSelect is the builder for selecting fields of MessageScore entities.
type MessageScoreSelect struct {
	*MessageScoreQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mss *MessageScoreSelect) Aggregate(fns ...AggregateFunc) *MessageScoreSelect {
	mss.fns = append(mss.fns, fns...)
	return mss
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MessageScoreSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mss.ctx, ent.OpQuerySelect)
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MessageScoreQuery, *MessageScoreSelect](ctx, mss.MessageScoreQuery, mss, mss.inters, v)
}

func (mss *MessageScoreSelect) sqlScan(ctx context.Context, root *MessageScoreQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mss.fns))
	for _, fn := range mss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
