// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lukepeltier/discordle/ent/messagescore"
	"github.com/lukepeltier/discordle/ent/predicate"
)

// MessageScoreDelete is the builder for deleting a MessageScore entity.
type MessageScoreDelete struct {
	config
	hooks    []Hook
	mutation *MessageScoreMutation
}

// Where appends a list predicates to the MessageScoreDelete builder.
func (msd *MessageScoreDelete) Where(ps ...predicate.MessageScore) *MessageScoreDelete {
	msd.mutation.Where(ps...)
	return msd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (msd *MessageScoreDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, msd.sqlExec, msd.mutation, msd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (msd *MessageScoreDelete) ExecX(ctx context.Context) int {
	n, err := msd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (msd *MessageScoreDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(messagescore.Table, sqlgraph.NewFieldSpec(messagescore.FieldID, field.TypeInt))
	if ps := msd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, msd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	msd.mutation.done = true
	return affected, err
}

// MessageScoreDeleteOne is the builder for deleting a single MessageScore entity.
type MessageScoreDeleteOne struct {
	msd *MessageScoreDelete
}

// Where appends a list predicates to the MessageScoreDelete builder.
func (msdo *MessageScoreDeleteOne) Where(ps ...predicate.MessageScore) *MessageScoreDeleteOne {
	msdo.msd.mutation.Where(ps...)
	return msdo
}

// Exec executes the deletion query.
func (msdo *MessageScoreDeleteOne) Exec(ctx context.Context) error {
	n, err := msdo.msd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{messagescore.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (msdo *MessageScoreDeleteOne) ExecX(ctx context.Context) {
	if err := msdo.Exec(ctx); err != nil {
		panic(err)
	}
}
