//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Admins = Admins.FromSchema(schema)
	Collections = Collections.FromSchema(schema)
	Externalauths = Externalauths.FromSchema(schema)
	Migrations = Migrations.FromSchema(schema)
	Params = Params.FromSchema(schema)
	DiscordMembers = DiscordMembers.FromSchema(schema)
	Guesses = Guesses.FromSchema(schema)
	Messages = Messages.FromSchema(schema)
	Users = Users.FromSchema(schema)
}
