// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Blacklist is the predicate function for blacklist builders.
type Blacklist func(*sql.Selector)

// DiscordMember is the predicate function for discordmember builders.
type DiscordMember func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// MessageScore is the predicate function for messagescore builders.
type MessageScore func(*sql.Selector)
